#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'
username="anthony"
hostname="arch-linux"
pass='5576'
sleep=8

echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------'

echo -e "Server = http://ftp.byfly.by/pub/archlinux/\$repo/os/\$arch \nServer = http://mirror.datacenter.by/pub/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
pacman -Sy sed --noconfirm

echo -e "\n"
echo '--------------------------------------------------'
echo '|            disk format                         |'
echo '--------------------------------------------------'

# Типы дисков 
# MBR GPT
#  ef C12A7328-F81F-11D2-BA4B-00A0C93EC93B EFI
#  82 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F SWAP linux
#     4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 Корень linux (x86-64)
#  83 0FC63DAF-8483-4772-8E79-3D69D8477DE4 linux
#     933AC7E1-2EB4-4F13-B844-0E14E2AEF915 linux home
#   b EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 Microsoft
#   5                                      Расширенный раздел для MBR

echo ">> rasmetka diska"
echo 'label: dos' | sfdisk /dev/sda
sleep $sleep
echo 'size=9G,   type=83' | sfdisk -a /dev/sda #/
sleep $sleep
#echo 'size=60G,  type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7' | sfdisk -a /dev/vda #/mnt/win

echo ">> format disk"
echo 'y' | mkfs.ext4 /dev/sda1 -L Arch
sleep $sleep
#echo 'y' | mkfs.ntfs -Q /dev/sda5 -L win

echo ">> mount disk"
mount /dev/sda1 /mnt
#mkdir -p /mnt/mnt/win
#mount /dev/sda4 /mnt/mnt/win

sleep $sleep

echo '--------------------------------------------------'
echo '|             install Arch Linux                 |'
echo '--------------------------------------------------'

echo '>> install Arch GNU'
pacstrap -i /mnt base base-devel linux linux-firmware --noconfirm
sleep $sleep

echo '>> nastroika montirovannya'
genfstab -L -p -P /mnt >> /mnt/etc/fstab

mkdir -p /mnt/home/$username/
cp -f install.sh /mnt/home/$username/
sleep $sleep

echo ">> install"
arch-chroot /mnt sh -c "$(cat chroot)" $username $hostname $pass
sleep $sleep

echo '--------------------------------------------------'
echo '|                 reboot                         |'
echo '--------------------------------------------------'
echo '>> reboot'
umount -R /mnt/
#reboot
