#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'
username="user"
hostname="VIRTUAL"
pass='123'

echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname
echo '--------------------------------------------------'

echo "Server = http://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
pacman -Sy sed --noconfirm

echo -e "\n"
echo '--------------------------------------------------'
echo '|             Форматирование диска               |'
echo '--------------------------------------------------'

# Типы дисков 
# MBR GPT
#  ef C12A7328-F81F-11D2-BA4B-00A0C93EC93B EFI
#  82 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F SWAP linux
#     4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709 Корень linux (x86-64)
#  83 0FC63DAF-8483-4772-8E79-3D69D8477DE4 linux
#     933AC7E1-2EB4-4F13-B844-0E14E2AEF915 linux home
#   b EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 Microsoft
#   5                                      Расширенный раздел для MBR

echo ">> Разметка диска"
echo 'label: gpt' | sfdisk /dev/sda
echo 'size=2G,   type=0657FD6D-A4AB-43C4-84E5-0933C84B4F4F' | sfdisk -a /dev/vda #swap
echo 'size=100M, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B' | sfdisk -a /dev/vda #/boot
echo 'size=15G,  type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709' | sfdisk -a /dev/vda #/
echo 'size=10G,  type=933AC7E1-2EB4-4F13-B844-0E14E2AEF915' | sfdisk -a /dev/vda #/home
#echo 'size=60G,  type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7' | sfdisk -a /dev/vda #/mnt/win

echo ">> Форматирование разделов"
echo 'y' | mkswap /dev/vda1 -L swap
echo 'y' | mkfs.ext4 /dev/vda3 -L Arch
echo 'y' | mkfs.fat -F32 /dev/vda2 -n EFI
echo 'y' | mkfs.ext4 /dev/vda4 -L home
#echo 'y' | mkfs.ntfs -Q /dev/sda5 -L win

echo ">> Подключение разделов"
swapon /dev/vda1
mount /dev/vda3 /mnt
mkdir -p /mnt/boot
mount /dev/vda2 /mnt/boot
mkdir -p /mnt/home
mount /dev/vda4 /mnt/home
#mkdir -p /mnt/mnt/win
#mount /dev/sda4 /mnt/mnt/win

echo '--------------------------------------------------'
echo '|             Установка Arch Linux               |'
echo '--------------------------------------------------'

echo '>> Установка Arch GNU'
pacstrap -i /mnt base base-devel linux linux-firmware --noconfirm

echo '>> Hacтройка точек монтирования'
genfstab -L -p -P /mnt >> /mnt/etc/fstab

mkdir -p /mnt/home/$username/
cp -f install.sh /mnt/home/$username/

echo ">> Установка"
arch-chroot /mnt sh -c "$(cat chroot)" $username $hostname $pass

echo '--------------------------------------------------'
echo '|                 Перезагрузка                   |'
echo '--------------------------------------------------'
umount -R /mnt/
reboot
