#!/bin/bash
#curl -i https://git.io -F "url=https://raw.githubusercontent.com/like913/arch-install/master/wget-arch-install" -F "code=wget-arch-install"

wget https://raw.githubusercontent.com/like913/arch-install/master/ru.sh
# Запуск руссификации
sh ./ru.sh

# Загрузка скриптов
wget https://notabug.org/like_913/arch-install/raw/master/install
wget https://notabug.org/like_913/arch-install/raw/master/chroot
wget https://notabug.org/like_913/arch-install/raw/master/install.sh

# Назначение прав на исполнениие кода
chmod +x install
